### ISSUE TITLE
iAd.showBannerAtXY not working - banner always shows in BOTTOM_CENTER

### ISSUE THREAD

**Issue by feeling99** [floatinghotpot/cordova-iad-pro#11]
Hi,

I am testing with ios 9.2, iphone 6 simulator.

with the given test page, in "show at XY" section, no matter what I input, the ad banner is always shown in the BOTTOM_CENTER.
I have tried these combination: (0,0), (0,20), (0,-20), (20,0), (-20,0), (20,20)

what test value should I use?

regards,

**Comment by floatinghotpot** [comment]
Did you add option `overlap:true` ?

**Comment by feeling99** [comment]
yeah overlap:true solved it.
thanks
