### ISSUE TITLE
After reinstalling plugin, error building cordova

### ISSUE THREAD

**Issue by braianj** [floatinghotpot/cordova-iad-pro#7]
When building Cordova i have this error

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_GenericAdPlugin", referenced from:
      _OBJC_CLASS_$_iAdPlugin in iAdPlugin.o
  "_OBJC_METACLASS_$_GenericAdPlugin", referenced from:
      _OBJC_METACLASS_$_iAdPlugin in iAdPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Cordova cli 5.0.0

Installed plugins

> com.darktalker.cordova.screenshot 0.1.1 "Screenshot"
> com.google.cordova.admob 2.7.7 "AdMob Plugin Pro"
> com.google.playservices 19.0.0 "Google Play Services for Android"
> com.rjfun.cordova.extension 1.1.4 "Cordova Plugin Extension"
> com.rjfun.cordova.iad 2.0.4 "iAd PluginPro"
> cordova-plugin-geolocation 1.0.0 "Geolocation"
> cordova-plugin-whitelist 1.0.1-dev "Whitelist"
> nl.x-services.plugins.socialsharing 4.3.18 "SocialSharing"
> org.apache.cordova.camera 0.3.6 "Camera"
> org.apache.cordova.network-information 0.2.15 "Network Information"
> org.apache.cordova.statusbar 0.1.10 "StatusBar"

**Comment by floatinghotpot** [comment]
I've tested the plugin again, no problem. 

You can try removing the ios platform and add it back.

**Comment by braianj** [comment]
yes, that solve the problem. Why happend that? i make i lot on xcode, and i need to make everything again

**Comment by floatinghotpot** [comment]
It's a tricky problem of cordova CLI.

**Comment by braianj** [comment]
Thanks!
